# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - NochipaCloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_790c2c54cd7a441fa9c6e111cfed0218 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e0794dae7c9547cd9e0422d3c73ff139 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_790c2c54cd7a441fa9c6e111cfed0218 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'NochipaCloud'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_de80bdeced01498fba5c7791fca632ed }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_790c2c54cd7a441fa9c6e111cfed0218 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'